In [10]:
import torch
from sklearn.datasets import make_classification

In [11]:
x,y = make_classification(
    n_samples=10 ,
    n_features = 2,
    n_informative=2,
    n_redundant=0,
    n_classes=2,
    random_state=42
)

In [12]:
x.shape

(10, 2)

In [13]:
x = torch.tensor(x , dtype=torch.float32)
y = torch.tensor(y,dtype=torch.long)

In [14]:
x

tensor([[ 1.0683, -0.9701],
        [-1.1402, -0.8388],
        [-2.8954,  1.9769],
        [-0.7206, -0.9606],
        [-1.9629, -0.9923],
        [-0.9382, -0.5430],
        [ 1.7273, -1.1858],
        [ 1.7774,  1.5116],
        [ 1.8997,  0.8344],
        [-0.5872, -1.9717]])

In [15]:
y

tensor([1, 0, 0, 0, 0, 1, 1, 1, 1, 0])

In [16]:
from torch.utils.data import Dataset , DataLoader

In [26]:
class CustomDataset(Dataset):
  def __init__(self,features , labels):
    self.features = features
    self.labels = labels

  def __len__(self):
    return self.features.shape[0]

  def __getitem__(self,idx):
    return self.features[idx] , self.labels[idx]



In [27]:
dataset = CustomDataset(x,y)

len(dataset)

10

In [28]:
dataset[1]

(tensor([-1.1402, -0.8388]), tensor(0))

In [29]:
dataloader =DataLoader(dataset,batch_size=2,shuffle=True)

In [30]:
for batch_features , batchloaders in  dataloader:
  print(batch_features)
  print(batchloaders)
  print("-"*50)

tensor([[-1.1402, -0.8388],
        [ 1.0683, -0.9701]])
tensor([0, 1])
--------------------------------------------------
tensor([[ 1.7273, -1.1858],
        [-0.5872, -1.9717]])
tensor([1, 0])
--------------------------------------------------
tensor([[-0.9382, -0.5430],
        [ 1.7774,  1.5116]])
tensor([1, 1])
--------------------------------------------------
tensor([[-1.9629, -0.9923],
        [-2.8954,  1.9769]])
tensor([0, 0])
--------------------------------------------------
tensor([[-0.7206, -0.9606],
        [ 1.8997,  0.8344]])
tensor([0, 1])
--------------------------------------------------
